### ISSUE TITLE
Group chats export

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [coldmind/vk-dialogue-export.py#1]
I'm using your script to export messages and it works awesome. But it seems there is no way to export group chats. Do you plan to add group chats export support? Thanks!

**Comment by coldmind** [comment]
Hi.
I don't know now, how group chat differ from normal chat in VK API, i will take a look for this.

**Comment by lyubomyr-shaydariv** [comment]
@coldmind 
Hi, I seem to have managed to export group chats. Please review my pull request.

**Comment by lyubomyr-shaydariv** [comment]
Done in 2f7fd4c03f1e6f7d37bc8ba8925784bff4e8f9f9.
